Common Modules - v1 proposal
ChannelApe/channelape-typescript-web-service-sdk pull request #1
Opened 2018-08-28 15:19 UTC by csimko

This SDK module will house many common services that are used across integrations with ChannelApe.
The SDK includes:

- ChannelApeActionsController
  - A generic controller that handles starting and stopping channel ape actions and automatically calling update
- AdditionalFieldService
- DecompressionService
- XmlParsingService
  - Converts XML to JS objects and vice versa
- SqsMessageService
- Secrets

2018-08-28 15:43 UTC, rjdavis3 commented
@csimko I changed your PR to merge into develop instead of master since these are new features.

2018-08-29 11:10 UTC, rjdavis3 requested changes
Please implement my requested changes then I will merge your pull request into develop.

You also need to fix all the Sonar issues here:
https://sonarcloud.io/project/issues?branch=feature%2Freal-ca-actions-controller-sqs-functions&id=channelape-typescript-web-service-sdk&resolved=false

We need to figure out a better way to publish early releases to npm. I'll try to figure that out on the develop branch.

These alpha versions that you are publishing are getting the latest tag. We should reserve latest for master branch builds only.

2018-08-29 11:10 UTC, rjdavis3 commented on package-lock.json
> +				"@fimbul/ymir": "^0.11.0",
My package-lock file is differing a lot from this one. Can you run `npm install` and commit it again?

2018-08-29 11:10 UTC, rjdavis3 commented on src/channelape/controller/ChannelApeActionsController.ts
> +          this.handleError(err, actionId);
I am still not confident that we fixed the issue with where health check update setIntervals are not cleared for completed/errored actions.

I wonder if maybe this is the culprit here?

Looks like we are only clearing the update interval if a response has already been sent to the client. I would think we we would want to clear the interval regardless of whether the child controller sent a response or we need to send the generic error response you have in this method.

Please prove this out with some unit tests before making any code changes. It should be easy to see if the setInterval remains when the child controller bubbles up an error before sending a response to the client.

2018-08-29 11:10 UTC, rjdavis3 commented on test/channelape/controller/ChannelApeActionsController.spec.ts
> +      .then(() => {
Assert that the healthcheck setInterval has been cleared

2018-08-29 11:10 UTC, rjdavis3 commented on test/channelape/controller/ChannelApeActionsController.spec.ts
> +      .then(() => {
Assert that the healthcheck setInterval has been cleared

2018-08-29 11:10 UTC, rjdavis3 commented on src/service/decompressionService/DecompressionService.ts
> +export default class DecompressionService {
Please change the folder to src/decompression/service/DecompressionService.ts

2018-08-29 11:10 UTC, rjdavis3 commented on src/service/sqsMessageService/SqsMessageService.ts
> +export default class SqsMessageService {
Please change the folder to src/sqs/service/SqsMessageService.ts

2018-08-29 11:10 UTC, rjdavis3 commented on stryker.conf.js
>      thresholds: { high: 90, low: 70, break: 20 },
Please increase break to 63 since mutation coverage is currently at 65.66%

2018-08-29 11:10 UTC, rjdavis3 commented on src/channelape/controller/ChannelApeActionsController.ts
> +  private updateHealthCheckInterval: NodeJS.Timer | undefined = undefined;
This assignment to undefined is not necessary. Please change to:

`private updateHealthCheckInterval: NodeJS.Timer | undefined;`

2018-08-29 11:10 UTC, rjdavis3 commented on src/service/sqsMessageService/SqsMessageService.ts
> +  ): void {
I find functions that have return methods much clearer to look at then those that change values of object references passed to them and are void.

You should be able to move this logic into getAllMessages and use a while loop instead of recursion. Then you won't need a helper function like getMessages.

2018-08-29 11:10 UTC, rjdavis3 commented on src/service/sqsMessageService/SqsMessageService.ts
> +      let combinedMessages = messages;
This variable is not needed. Please remove it.

2018-08-29 11:10 UTC, rjdavis3 commented on src/service/sqsMessageService/SqsMessageService.ts
> +  private finalizeMessages(
Why do you do this in bulk after retrieving all the messages? If you instead called decompcressMessageBody with the SQS Message options then you wouldn't need this method. I think that may help readability.

Basically I think the flow should be something like:
* Retrieve page of messages
* Retry if needed
* Decompress each message on page
* Loop through each page of messages until no more messages are on the queue
* Return all messages.

This would improve readability.

2018-08-29 11:10 UTC, rjdavis3 commented on src/service/sqsMessageService/model/GetMessageOptions.ts
> +export default interface GetMessageOption {
Move this to src/sqs/model/GetMessageOption.ts

2018-08-29 11:10 UTC, rjdavis3 commented on src/index.ts
>  export { default as Secrets } from './service/Secrets';
Please move Secrets.ts to src/environment/model/Secrets.ts to stay consist with the other package changes.

Therefore we should have the following top level packages:
* channelape
* environment
* sqs
* parser
* decompression

2018-08-29 11:10 UTC, rjdavis3 commented on src/index.ts
>  export { default as Secrets } from './service/Secrets';
@csimko  @frankMazzarella  I'm open to other suggestions here too. I just thing we should keep the structure of feature then function (i.e. orders -> controllers, etc.) even for our common code.

2018-08-29 11:10 UTC, rjdavis3 commented on src/index.ts
>  export { default as Secrets } from './service/Secrets';
Can you also add the following field to Secrets.ts:

`
    CHANNEL_APE_REQUEST_TIMEOUT: '300000',
    CHANNEL_APE_MAX_REQUEST_RETRY_TIMEOUT: '600000',
`

2018-08-29 20:42 UTC, csimko commented on stryker.conf.js
>      thresholds: { high: 90, low: 70, break: 20 },
@rjdavis3  I will up this but Stryker was giving varying mutation scores on this repo. I identified what was causing the variation but I have no idea how to resolve it. I opened an issue with Stryker and will need to update that thread with what I found.

Long story short, Stryker does not seem to function properly when timing is involved. This is twice that we've seen this happen. In this repo the mutation score is getting confused by the healthcheck interval. When removing all of that logic the mutation score is stable. Another project we were working on, @frankMazzarella  utilized sinon's useFakeTimers but Stryker failed completely when that was used, even though the unit tests passed.

2018-08-29 21:28 UTC, csimko commented
@rjdavis3  If you could merge this into develop and publish that would be awesome as this is the only thing keeping me from opening the review for the other work.
The package is currently at version *0.1.0-develop.2*

2018-08-30 12:08 UTC, rjdavis3 requested changes
@csimko I really like the native promises you put in this code. I think we should change all of the exported classes within index.ts to return native promises instead of Q promises for the public functions. This way external developers are not forced to use Q. This follows the same principle we used for channelape-sdk.

From what I can see here is where the native promise changes need to be made:
* XmlParsingService
* DecompressionService
* SqsMessageService

Please make these changes in addition to my other comments. Then I will merge your pull request into develop.

2018-08-30 12:08 UTC, rjdavis3 commented on src/sqs/service/SqsMessageService.ts
> +        deferred.reject(`Message "${message.MessageId}" not acknowledged.`);
You are hiding the error message from the delete message request here. Please include the err in your string here.

2018-08-30 12:08 UTC, rjdavis3 commented on src/sqs/service/SqsMessageService.ts
> +  public async getAllMessages(options?: GetMessageOptions): Promise<AWS.SQS.Message[]> {
I find it odd that this public function returns a native promise while deleteMessage returns Q. Please either change deleteMessage to return a native promise _or_ change this function to return a Q promise.

2018-08-30 12:08 UTC, rjdavis3 commented on src/sqs/service/SqsMessageService.ts
> +  public acknowledgeMessage(message: AWS.SQS.Message): Q.Promise<any> {
Do you need to return a promise of type any? Please change this to string.

You change change line 58 to reject with a string instead of Error and that should suffice.

2018-08-30 13:44 UTC, csimko commented
@rjdavis3  I just pushed the last of the changes that you requested to this branch. I believe it is ready to be merged into develop

2018-08-30 15:02 UTC, rjdavis3 requested changes
There are still some services that are using Q instead of native promises for their public functions. I mentioned this in your last review. Please remedy this then let me know and I will accept the PR.

Also I deleted all of the tags that you pushed. Every tag can be considered a release (that is what GitHub flags them as) but we have not released any code for this repo yet. Our first tag will be added during GitFlow release and will be 0.1.0

2018-08-30 15:02 UTC, rjdavis3 commented on src/parser/service/XmlParsingService.ts
> +  public static toXml(obj: any): Q.Promise<string> {
Change this to return a native promise instead of a Q promise since it is a public function on a class that you are exporting in index.ts.

2018-08-30 15:02 UTC, rjdavis3 commented on src/parser/service/XmlParsingService.ts
> +  public static fromXml<T>(xml: string): Q.Promise<T> {
Change this to return a native promise instead of a Q promise since it is a public function on a class that you are exporting in index.ts.

2018-08-30 15:02 UTC, rjdavis3 commented on src/decompression/service/DecompressionService.ts
> +  public static decompress(value: string): Q.Promise<string> {
Change this to return a native promise instead of a Q promise since it is a public function on a class that you are exporting in index.ts.

2018-08-30 15:20 UTC, csimko commented
@rjdavis3  XmlParsingService and Decompression service no longer rely on Q. I kept it in the channel ape actions controller as I'm not sure if that would be a breaking change and I feel that could be addressed at some future point.

2018-08-30 15:26 UTC, rjdavis3 approved these changes

2018-08-30 15:29 UTC, merged